### ISSUE TITLE
Labels are broken.

### ISSUE THREAD

**Issue by CitizenFoffie** [leechwort/knob-scale-generator#17]
```
Traceback (most recent call last):
  File "C:\Users\citiz\AppData\Roaming\inkscape\extensions\org.inkscape.extension.11422\knob-scale-generator-master\render_knob_scale.py", line 286, in <module>
    e.run()
  File "F:\Studio\Inkscape\share\inkscape\extensions\inkex\base.py", line 231, in run
    self.save_raw(self.effect())
  File "C:\Users\citiz\AppData\Roaming\inkscape\extensions\org.inkscape.extension.11422\knob-scale-generator-master\render_knob_scale.py", line 268, in effect
    self.draw_text(tick_text, radius + tick_length + text_spacing,
  File "C:\Users\citiz\AppData\Roaming\inkscape\extensions\org.inkscape.extension.11422\knob-scale-generator-master\render_knob_scale.py", line 131, in draw_text
    text.set('style', str(inkex.Style(style)))
  File "F:\Studio\Inkscape\share\inkscape\extensions\inkex\styles.py", line 121, in __init__
    super().__init__(style)
  File "F:\Studio\Inkscape\share\inkscape\extensions\inkex\styles.py", line 274, in __setitem__
    value = BaseStyleValue.factory(attr_name=key, value=value)
  File "F:\Studio\Inkscape\share\inkscape\extensions\inkex\properties.py", line 184, in factory
    return valuetype(declaration, attr_name, value, important)
  File "F:\Studio\Inkscape\share\inkscape\extensions\inkex\properties.py", line 369, in __init__
    super().__init__(declaration, attr_name, value, important)
  File "F:\Studio\Inkscape\share\inkscape\extensions\inkex\properties.py", line 62, in __init__
    _ = self.parse_value()  # check that we can parse this value
  File "F:\Studio\Inkscape\share\inkscape\extensions\inkex\properties.py", line 104, in parse_value
    return self._parse_value(self.value, element)
  File "F:\Studio\Inkscape\share\inkscape\extensions\inkex\properties.py", line 374, in _parse_value
    raise ValueError(
ValueError: Value 'center' is invalid for the property alignment-baseline. Allowed values are: ['baseline', 'text-bottom', 'alphabetic', 'ideographic', 'middle', 'central', 'mathematical', 'text-top', 'inherit']

```

**Comment by vmario89** [comment]
hi. can you paste the settings for the knob generator you entered in? and what version of inkscape do you use?

**Comment by CitizenFoffie** [comment]
The most recent(2.1), and this only happens when I enable Labels, tried it on stock settings to test.

**Comment by vmario89** [comment]
does this happen with https://gitea.fablabchemnitz.de/FabLab_Chemnitz/mightyscape-1.X/src/branch/master/extensions/fablabchemnitz/knob_scale too? i do not have the 1.2 on Fedora 35 yet, still working with 1.1 - there it works fine

**Comment by UAP-Hunter** [comment]
The issue is in the `draw_text` definition.

```
style = {
                'text-align' : 'center',
                 'text-anchor': 'middle',
                 'alignment-baseline' : 'center',
                 'font-size' : str(text_size),
                 'vertical-align' : 'middle'
                 }
```
Change from `'alignment-baseline' : 'center',` to `''alignment-baseline' : 'central',`

Hope this helps.

**Comment by DimUrm** [comment]
It doesn't work again
This happens only when I enable Labels
Version 1.2 & Version 1.3
```
File "C:\Users\User\AppData\Roaming\inkscape\extensions\render_knob_scale.py", line 286, in <module>
    e.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 231, in run
    self.save_raw(self.effect())
  File "C:\Users\User\AppData\Roaming\inkscape\extensions\render_knob_scale.py", line 268, in effect
    self.draw_text(tick_text, radius + tick_length + text_spacing,
  File "C:\Users\User\AppData\Roaming\inkscape\extensions\render_knob_scale.py", line 131, in draw_text
    text.set('style', str(inkex.Style(style)))
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\styles.py", line 121, in __init__
    super().__init__(style)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\styles.py", line 274, in __setitem__
    value = BaseStyleValue.factory(attr_name=key, value=value)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\properties.py", line 184, in factory
    return valuetype(declaration, attr_name, value, important)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\properties.py", line 369, in __init__
    super().__init__(declaration, attr_name, value, important)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\properties.py", line 62, in __init__
    _ = self.parse_value()  # check that we can parse this value
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\properties.py", line 104, in parse_value
    return self._parse_value(self.value, element)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\properties.py", line 374, in _parse_value
    raise ValueError(
ValueError: Value 'center' is invalid for the property alignment-baseline. Allowed values are: ['baseline', 'text-bottom', 'alphabetic', 'ideographic', 'middle', 'central', 'mathematical', 'text-top', 'inherit']
```
